# Welcome to Jekyll!

title: JammingWithJAM
email: ""
description: >-
  CyberJournal Logs – an evolving knowledge base on ethical hacking, bug bounty, and secure development.
  Where code meets curiosity, and every vulnerability unfolds a lesson.
  I believe persistence is the true power of every cyber warrior.

  These logs are more than just dry theory — they're a real-world guide for anyone walking the path from zero to root.
  Join me for hands-on tips, practical tricks, and sharp insights that make cybersecurity simple, direct, and worth every byte.

twitter_username: username
github_username: WEAREJAM
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "WeAreJam"
  avatar: "/JAM.jpg"
  bio: >-
    I'm JAM — cybersecurity enthusiast, bug bounty learner, and ethical hacker in progress.
    Through this blog, I document everything I break (legally 😉), learn, and build.
    Tools I love: Burp Suite, OWASP BWA, Kali Linux, DVWA.
    This is where my curiosity and persistence meet. Let's grow together.

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WEAREJAM"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jahnavi-makaraju-17b322371/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
